#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOKO_ABC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="stok_db")]
	public partial class StokDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbarang(barang instance);
    partial void Updatebarang(barang instance);
    partial void Deletebarang(barang instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertpembeli(pembeli instance);
    partial void Updatepembeli(pembeli instance);
    partial void Deletepembeli(pembeli instance);
    partial void Insertpembelian_barang(pembelian_barang instance);
    partial void Updatepembelian_barang(pembelian_barang instance);
    partial void Deletepembelian_barang(pembelian_barang instance);
    partial void Insertpenjualan_barang(penjualan_barang instance);
    partial void Updatepenjualan_barang(penjualan_barang instance);
    partial void Deletepenjualan_barang(penjualan_barang instance);
    partial void Insertsupplier(supplier instance);
    partial void Updatesupplier(supplier instance);
    partial void Deletesupplier(supplier instance);
    #endregion
		
		public StokDataContext() : 
				base(global::TOKO_ABC.Properties.Settings.Default.stok_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StokDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StokDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<barang> barangs
		{
			get
			{
				return this.GetTable<barang>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<pembeli> pembelis
		{
			get
			{
				return this.GetTable<pembeli>();
			}
		}
		
		public System.Data.Linq.Table<pembelian_barang> pembelian_barangs
		{
			get
			{
				return this.GetTable<pembelian_barang>();
			}
		}
		
		public System.Data.Linq.Table<penjualan_barang> penjualan_barangs
		{
			get
			{
				return this.GetTable<penjualan_barang>();
			}
		}
		
		public System.Data.Linq.Table<supplier> suppliers
		{
			get
			{
				return this.GetTable<supplier>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.barang")]
	public partial class barang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_barang;
		
		private string _nama_barang;
		
		private System.Nullable<int> _harga;
		
		private System.Nullable<int> _id_supplier;
		
		private string _jns_barang;
		
		private System.Nullable<int> _jumlah;
		
		private string _keterangan;
		
		private EntitySet<pembelian_barang> _pembelian_barangs;
		
		private EntitySet<penjualan_barang> _penjualan_barangs;
		
		private EntityRef<supplier> _supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_barangChanging(int value);
    partial void Onid_barangChanged();
    partial void Onnama_barangChanging(string value);
    partial void Onnama_barangChanged();
    partial void OnhargaChanging(System.Nullable<int> value);
    partial void OnhargaChanged();
    partial void Onid_supplierChanging(System.Nullable<int> value);
    partial void Onid_supplierChanged();
    partial void Onjns_barangChanging(string value);
    partial void Onjns_barangChanged();
    partial void OnjumlahChanging(System.Nullable<int> value);
    partial void OnjumlahChanged();
    partial void OnketeranganChanging(string value);
    partial void OnketeranganChanged();
    #endregion
		
		public barang()
		{
			this._pembelian_barangs = new EntitySet<pembelian_barang>(new Action<pembelian_barang>(this.attach_pembelian_barangs), new Action<pembelian_barang>(this.detach_pembelian_barangs));
			this._penjualan_barangs = new EntitySet<penjualan_barang>(new Action<penjualan_barang>(this.attach_penjualan_barangs), new Action<penjualan_barang>(this.detach_penjualan_barangs));
			this._supplier = default(EntityRef<supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_barang
		{
			get
			{
				return this._id_barang;
			}
			set
			{
				if ((this._id_barang != value))
				{
					this.Onid_barangChanging(value);
					this.SendPropertyChanging();
					this._id_barang = value;
					this.SendPropertyChanged("id_barang");
					this.Onid_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_barang", DbType="VarChar(255)")]
		public string nama_barang
		{
			get
			{
				return this._nama_barang;
			}
			set
			{
				if ((this._nama_barang != value))
				{
					this.Onnama_barangChanging(value);
					this.SendPropertyChanging();
					this._nama_barang = value;
					this.SendPropertyChanged("nama_barang");
					this.Onnama_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Int")]
		public System.Nullable<int> harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_supplier", DbType="Int")]
		public System.Nullable<int> id_supplier
		{
			get
			{
				return this._id_supplier;
			}
			set
			{
				if ((this._id_supplier != value))
				{
					if (this._supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_supplierChanging(value);
					this.SendPropertyChanging();
					this._id_supplier = value;
					this.SendPropertyChanged("id_supplier");
					this.Onid_supplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jns_barang", DbType="VarChar(255)")]
		public string jns_barang
		{
			get
			{
				return this._jns_barang;
			}
			set
			{
				if ((this._jns_barang != value))
				{
					this.Onjns_barangChanging(value);
					this.SendPropertyChanging();
					this._jns_barang = value;
					this.SendPropertyChanged("jns_barang");
					this.Onjns_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah", DbType="Int")]
		public System.Nullable<int> jumlah
		{
			get
			{
				return this._jumlah;
			}
			set
			{
				if ((this._jumlah != value))
				{
					this.OnjumlahChanging(value);
					this.SendPropertyChanging();
					this._jumlah = value;
					this.SendPropertyChanged("jumlah");
					this.OnjumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keterangan", DbType="VarChar(255)")]
		public string keterangan
		{
			get
			{
				return this._keterangan;
			}
			set
			{
				if ((this._keterangan != value))
				{
					this.OnketeranganChanging(value);
					this.SendPropertyChanging();
					this._keterangan = value;
					this.SendPropertyChanged("keterangan");
					this.OnketeranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="barang_pembelian_barang", Storage="_pembelian_barangs", ThisKey="id_barang", OtherKey="id_barang")]
		public EntitySet<pembelian_barang> pembelian_barangs
		{
			get
			{
				return this._pembelian_barangs;
			}
			set
			{
				this._pembelian_barangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="barang_penjualan_barang", Storage="_penjualan_barangs", ThisKey="id_barang", OtherKey="id_barang")]
		public EntitySet<penjualan_barang> penjualan_barangs
		{
			get
			{
				return this._penjualan_barangs;
			}
			set
			{
				this._penjualan_barangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="supplier_barang", Storage="_supplier", ThisKey="id_supplier", OtherKey="id_supplier", IsForeignKey=true)]
		public supplier supplier
		{
			get
			{
				return this._supplier.Entity;
			}
			set
			{
				supplier previousValue = this._supplier.Entity;
				if (((previousValue != value) 
							|| (this._supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._supplier.Entity = null;
						previousValue.barangs.Remove(this);
					}
					this._supplier.Entity = value;
					if ((value != null))
					{
						value.barangs.Add(this);
						this._id_supplier = value.id_supplier;
					}
					else
					{
						this._id_supplier = default(Nullable<int>);
					}
					this.SendPropertyChanged("supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pembelian_barangs(pembelian_barang entity)
		{
			this.SendPropertyChanging();
			entity.barang = this;
		}
		
		private void detach_pembelian_barangs(pembelian_barang entity)
		{
			this.SendPropertyChanging();
			entity.barang = null;
		}
		
		private void attach_penjualan_barangs(penjualan_barang entity)
		{
			this.SendPropertyChanging();
			entity.barang = this;
		}
		
		private void detach_penjualan_barangs(penjualan_barang entity)
		{
			this.SendPropertyChanging();
			entity.barang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private string _nama;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(255)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(255)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pembeli")]
	public partial class pembeli : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pembeli;
		
		private string _nama;
		
		private string _alamat;
		
		private string _no_telp;
		
		private EntitySet<penjualan_barang> _penjualan_barangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pembeliChanging(int value);
    partial void Onid_pembeliChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void Onno_telpChanging(string value);
    partial void Onno_telpChanged();
    #endregion
		
		public pembeli()
		{
			this._penjualan_barangs = new EntitySet<penjualan_barang>(new Action<penjualan_barang>(this.attach_penjualan_barangs), new Action<penjualan_barang>(this.detach_penjualan_barangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembeli", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pembeli
		{
			get
			{
				return this._id_pembeli;
			}
			set
			{
				if ((this._id_pembeli != value))
				{
					this.Onid_pembeliChanging(value);
					this.SendPropertyChanging();
					this._id_pembeli = value;
					this.SendPropertyChanged("id_pembeli");
					this.Onid_pembeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(255)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(255)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_telp", DbType="VarChar(255)")]
		public string no_telp
		{
			get
			{
				return this._no_telp;
			}
			set
			{
				if ((this._no_telp != value))
				{
					this.Onno_telpChanging(value);
					this.SendPropertyChanging();
					this._no_telp = value;
					this.SendPropertyChanged("no_telp");
					this.Onno_telpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pembeli_penjualan_barang", Storage="_penjualan_barangs", ThisKey="id_pembeli", OtherKey="id_pembeli")]
		public EntitySet<penjualan_barang> penjualan_barangs
		{
			get
			{
				return this._penjualan_barangs;
			}
			set
			{
				this._penjualan_barangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_penjualan_barangs(penjualan_barang entity)
		{
			this.SendPropertyChanging();
			entity.pembeli = this;
		}
		
		private void detach_penjualan_barangs(penjualan_barang entity)
		{
			this.SendPropertyChanging();
			entity.pembeli = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pembelian_barang")]
	public partial class pembelian_barang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pembelianbarang;
		
		private System.Nullable<int> _id_barang;
		
		private System.Nullable<int> _id_supplier;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private System.Nullable<int> _jumlah;
		
		private System.Nullable<int> _harga;
		
		private string _keterangan;
		
		private EntityRef<barang> _barang;
		
		private EntityRef<supplier> _supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pembelianbarangChanging(int value);
    partial void Onid_pembelianbarangChanged();
    partial void Onid_barangChanging(System.Nullable<int> value);
    partial void Onid_barangChanged();
    partial void Onid_supplierChanging(System.Nullable<int> value);
    partial void Onid_supplierChanged();
    partial void OntanggalChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalChanged();
    partial void OnjumlahChanging(System.Nullable<int> value);
    partial void OnjumlahChanged();
    partial void OnhargaChanging(System.Nullable<int> value);
    partial void OnhargaChanged();
    partial void OnketeranganChanging(string value);
    partial void OnketeranganChanged();
    #endregion
		
		public pembelian_barang()
		{
			this._barang = default(EntityRef<barang>);
			this._supplier = default(EntityRef<supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembelianbarang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pembelianbarang
		{
			get
			{
				return this._id_pembelianbarang;
			}
			set
			{
				if ((this._id_pembelianbarang != value))
				{
					this.Onid_pembelianbarangChanging(value);
					this.SendPropertyChanging();
					this._id_pembelianbarang = value;
					this.SendPropertyChanged("id_pembelianbarang");
					this.Onid_pembelianbarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barang", DbType="Int")]
		public System.Nullable<int> id_barang
		{
			get
			{
				return this._id_barang;
			}
			set
			{
				if ((this._id_barang != value))
				{
					if (this._barang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_barangChanging(value);
					this.SendPropertyChanging();
					this._id_barang = value;
					this.SendPropertyChanged("id_barang");
					this.Onid_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_supplier", DbType="Int")]
		public System.Nullable<int> id_supplier
		{
			get
			{
				return this._id_supplier;
			}
			set
			{
				if ((this._id_supplier != value))
				{
					if (this._supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_supplierChanging(value);
					this.SendPropertyChanging();
					this._id_supplier = value;
					this.SendPropertyChanged("id_supplier");
					this.Onid_supplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah", DbType="Int")]
		public System.Nullable<int> jumlah
		{
			get
			{
				return this._jumlah;
			}
			set
			{
				if ((this._jumlah != value))
				{
					this.OnjumlahChanging(value);
					this.SendPropertyChanging();
					this._jumlah = value;
					this.SendPropertyChanged("jumlah");
					this.OnjumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Int")]
		public System.Nullable<int> harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keterangan", DbType="VarChar(255)")]
		public string keterangan
		{
			get
			{
				return this._keterangan;
			}
			set
			{
				if ((this._keterangan != value))
				{
					this.OnketeranganChanging(value);
					this.SendPropertyChanging();
					this._keterangan = value;
					this.SendPropertyChanged("keterangan");
					this.OnketeranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="barang_pembelian_barang", Storage="_barang", ThisKey="id_barang", OtherKey="id_barang", IsForeignKey=true)]
		public barang barang
		{
			get
			{
				return this._barang.Entity;
			}
			set
			{
				barang previousValue = this._barang.Entity;
				if (((previousValue != value) 
							|| (this._barang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._barang.Entity = null;
						previousValue.pembelian_barangs.Remove(this);
					}
					this._barang.Entity = value;
					if ((value != null))
					{
						value.pembelian_barangs.Add(this);
						this._id_barang = value.id_barang;
					}
					else
					{
						this._id_barang = default(Nullable<int>);
					}
					this.SendPropertyChanged("barang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="supplier_pembelian_barang", Storage="_supplier", ThisKey="id_supplier", OtherKey="id_supplier", IsForeignKey=true)]
		public supplier supplier
		{
			get
			{
				return this._supplier.Entity;
			}
			set
			{
				supplier previousValue = this._supplier.Entity;
				if (((previousValue != value) 
							|| (this._supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._supplier.Entity = null;
						previousValue.pembelian_barangs.Remove(this);
					}
					this._supplier.Entity = value;
					if ((value != null))
					{
						value.pembelian_barangs.Add(this);
						this._id_supplier = value.id_supplier;
					}
					else
					{
						this._id_supplier = default(Nullable<int>);
					}
					this.SendPropertyChanged("supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.penjualan_barang")]
	public partial class penjualan_barang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_penjualanbarang;
		
		private System.Nullable<int> _id_pembeli;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private System.Nullable<int> _jumlah;
		
		private System.Nullable<int> _id_barang;
		
		private string _status;
		
		private EntityRef<barang> _barang;
		
		private EntityRef<pembeli> _pembeli;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_penjualanbarangChanging(int value);
    partial void Onid_penjualanbarangChanged();
    partial void Onid_pembeliChanging(System.Nullable<int> value);
    partial void Onid_pembeliChanged();
    partial void OntanggalChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalChanged();
    partial void OnjumlahChanging(System.Nullable<int> value);
    partial void OnjumlahChanged();
    partial void Onid_barangChanging(System.Nullable<int> value);
    partial void Onid_barangChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public penjualan_barang()
		{
			this._barang = default(EntityRef<barang>);
			this._pembeli = default(EntityRef<pembeli>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_penjualanbarang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_penjualanbarang
		{
			get
			{
				return this._id_penjualanbarang;
			}
			set
			{
				if ((this._id_penjualanbarang != value))
				{
					this.Onid_penjualanbarangChanging(value);
					this.SendPropertyChanging();
					this._id_penjualanbarang = value;
					this.SendPropertyChanged("id_penjualanbarang");
					this.Onid_penjualanbarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembeli", DbType="Int")]
		public System.Nullable<int> id_pembeli
		{
			get
			{
				return this._id_pembeli;
			}
			set
			{
				if ((this._id_pembeli != value))
				{
					if (this._pembeli.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pembeliChanging(value);
					this.SendPropertyChanging();
					this._id_pembeli = value;
					this.SendPropertyChanged("id_pembeli");
					this.Onid_pembeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah", DbType="Int")]
		public System.Nullable<int> jumlah
		{
			get
			{
				return this._jumlah;
			}
			set
			{
				if ((this._jumlah != value))
				{
					this.OnjumlahChanging(value);
					this.SendPropertyChanging();
					this._jumlah = value;
					this.SendPropertyChanged("jumlah");
					this.OnjumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barang", DbType="Int")]
		public System.Nullable<int> id_barang
		{
			get
			{
				return this._id_barang;
			}
			set
			{
				if ((this._id_barang != value))
				{
					if (this._barang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_barangChanging(value);
					this.SendPropertyChanging();
					this._id_barang = value;
					this.SendPropertyChanged("id_barang");
					this.Onid_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(255)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="barang_penjualan_barang", Storage="_barang", ThisKey="id_barang", OtherKey="id_barang", IsForeignKey=true)]
		public barang barang
		{
			get
			{
				return this._barang.Entity;
			}
			set
			{
				barang previousValue = this._barang.Entity;
				if (((previousValue != value) 
							|| (this._barang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._barang.Entity = null;
						previousValue.penjualan_barangs.Remove(this);
					}
					this._barang.Entity = value;
					if ((value != null))
					{
						value.penjualan_barangs.Add(this);
						this._id_barang = value.id_barang;
					}
					else
					{
						this._id_barang = default(Nullable<int>);
					}
					this.SendPropertyChanged("barang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pembeli_penjualan_barang", Storage="_pembeli", ThisKey="id_pembeli", OtherKey="id_pembeli", IsForeignKey=true)]
		public pembeli pembeli
		{
			get
			{
				return this._pembeli.Entity;
			}
			set
			{
				pembeli previousValue = this._pembeli.Entity;
				if (((previousValue != value) 
							|| (this._pembeli.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pembeli.Entity = null;
						previousValue.penjualan_barangs.Remove(this);
					}
					this._pembeli.Entity = value;
					if ((value != null))
					{
						value.penjualan_barangs.Add(this);
						this._id_pembeli = value.id_pembeli;
					}
					else
					{
						this._id_pembeli = default(Nullable<int>);
					}
					this.SendPropertyChanged("pembeli");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.supplier")]
	public partial class supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_supplier;
		
		private string _nama;
		
		private string _alamat;
		
		private string _no_telp;
		
		private EntitySet<barang> _barangs;
		
		private EntitySet<pembelian_barang> _pembelian_barangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_supplierChanging(int value);
    partial void Onid_supplierChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void Onno_telpChanging(string value);
    partial void Onno_telpChanged();
    #endregion
		
		public supplier()
		{
			this._barangs = new EntitySet<barang>(new Action<barang>(this.attach_barangs), new Action<barang>(this.detach_barangs));
			this._pembelian_barangs = new EntitySet<pembelian_barang>(new Action<pembelian_barang>(this.attach_pembelian_barangs), new Action<pembelian_barang>(this.detach_pembelian_barangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_supplier", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_supplier
		{
			get
			{
				return this._id_supplier;
			}
			set
			{
				if ((this._id_supplier != value))
				{
					this.Onid_supplierChanging(value);
					this.SendPropertyChanging();
					this._id_supplier = value;
					this.SendPropertyChanged("id_supplier");
					this.Onid_supplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(255)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(255)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_telp", DbType="VarChar(255)")]
		public string no_telp
		{
			get
			{
				return this._no_telp;
			}
			set
			{
				if ((this._no_telp != value))
				{
					this.Onno_telpChanging(value);
					this.SendPropertyChanging();
					this._no_telp = value;
					this.SendPropertyChanged("no_telp");
					this.Onno_telpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="supplier_barang", Storage="_barangs", ThisKey="id_supplier", OtherKey="id_supplier")]
		public EntitySet<barang> barangs
		{
			get
			{
				return this._barangs;
			}
			set
			{
				this._barangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="supplier_pembelian_barang", Storage="_pembelian_barangs", ThisKey="id_supplier", OtherKey="id_supplier")]
		public EntitySet<pembelian_barang> pembelian_barangs
		{
			get
			{
				return this._pembelian_barangs;
			}
			set
			{
				this._pembelian_barangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_barangs(barang entity)
		{
			this.SendPropertyChanging();
			entity.supplier = this;
		}
		
		private void detach_barangs(barang entity)
		{
			this.SendPropertyChanging();
			entity.supplier = null;
		}
		
		private void attach_pembelian_barangs(pembelian_barang entity)
		{
			this.SendPropertyChanging();
			entity.supplier = this;
		}
		
		private void detach_pembelian_barangs(pembelian_barang entity)
		{
			this.SendPropertyChanging();
			entity.supplier = null;
		}
	}
}
#pragma warning restore 1591
